### ISSUE TITLE
Unable to start Microsoft.R.Host process. Exception: R host process did not start on the machine.

### ISSUE THREAD

**Issue by SkrHo** [MikhailArkhipov/vscode-r#85]
Hi,

I am facing this problem now. I don't know how to solve it.  
![image](https://user-images.githubusercontent.com/95479887/168488923-a9b98a3e-09ec-481f-bec4-51241a4f35b2.png)

**Comment by nick-robo** [comment]
Same here. Installed the extension, dotnet and r, but I am getting this error every time I open VS Code now.

Platform: Linux 5.19.8-arch1-1 x86_64 GNU/Linux
R version: 4.2.1 (2022-06-23)
Dotnet version: 5.0.408

**Comment by hdiazf** [comment]
Same Here
Using Windows 11 22H2
R version: 4.2.1 (2022-06-23)
Dotnet 6

**Comment by MikhailArkhipov** [comment]
This was change in API in R. 0.30 should fix this.

**Comment by softboy99** [comment]
still have this problem for latest vscode and latest extension

**Comment by MikhailArkhipov** [comment]
See wrt Linux in https://github.com/MikhailArkhipov/vscode-r/issues/100. Can you try running from cmd line and see what happens.
